version: "3"
services:
  django_gunicorn:
    volumes:
    - static:/static
    env_file:
      - .env
    build:
      context: .
    container_name: django
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "3000:3000"
    depends_on:
      - django_gunicorn


volumes:
  static:
