# Generated by Django 4.0.1 on 2022-06-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dash_mode',
            field=models.BooleanField(default=False),
        ),
    ]
